### ISSUE TITLE
Too much data

### ISSUE THREAD

**Issue by Sumer6** [Seungwoo321/vue-pivottable#1]
Such errors are displayed: **[Vue warn]: Error in render: "RangeError: Maximum call stack size exceeded"** and **RangeError: Maximum call stack size exceeded**

**Comment by Seungwoo321** [comment]
Can you tell me more?

**Comment by Sumer6** [comment]
Having a lot of data in the table and when I add another column or row with a lot of data I get an errors.

There is probably some limited amount of data that can be displayed.

**Comment by ekohadim** [comment]
This is probably not the plugin issue.

Please check this one
[https://stackoverflow.com/questions/6095530/maximum-call-stack-size-exceeded-error](url)

**Comment by Seungwoo321** [comment]
Sorry. This cannot be fixed.
