### ISSUE TITLE
Is is possible to get PivotTable State

### ISSUE THREAD

**Issue by OdiljonQurbon** [Seungwoo321/vue-pivottable#14]
This feature would be very useful: save the PivotTable State generated with vue-pivottable-ui and reproduce it using vue-pivottable. [As in this example](https://pivottable.js.org/examples/onrefresh.html), from [FAQ](https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#accessingsaving-pivottable-state).
Thanks for great port!

**Comment by Seungwoo321** [comment]
Please wait , i will update as soon as possible. 
Your feedback is very good. :)

**Comment by ekohadim** [comment]
Hi - I agree with this suggestion. The parameters are not reactive at the moment. Anyway, thanks for the great port.

**Comment by Mihailoff** [comment]
`rows` and `cols` are in fact reactive, unfortunately `renderer-name` is not, this would be a bare minimum to save the state

**Comment by dyyce** [comment]
any update on this one? 👍

**Comment by Mihailoff** [comment]
`@onRefresh` does the magic, thanks @Seungwoo321 👏

**Comment by Seungwoo321** [comment]
> `@onRefresh` does the magic, thanks @Seungwoo321 👏

Update to the latest version of v-model.
