### ISSUE TITLE
export derivers from './helper/utils'

### ISSUE THREAD

**Issue by jupe** [Seungwoo321/vue-pivottable#19]
There is useful derivers in pivotable library but those are not exported in vue-pivottable. Could you export those so it's easier to use ? e.g. `derivers.bin`, `derivers.dateFormat` .

**Comment by adroit91** [comment]
Would be brilliant if this can be done!

**Comment by Seungwoo321** [comment]
Please check updated demo example code. [link](https://github.com/Seungwoo321/vue-pivottable/blob/master/demo/example-vue-cli3/src/App.vue)
