### ISSUE TITLE
Webpack: Module parse failed: Unexpected token (341:14)

### ISSUE THREAD

**Issue by leonardlin** [Seungwoo321/vue-pivottable#21]
I'm tried to use the module with my vuejs project.

I get the error below:

```
./node_modules/vue-pivottable/src/PivottableUi.js
Module parse failed: Unexpected token (341:14)
You may need an appropriate loader to handle this file type.
| 	  : h(Pivottable, {
|             props: {
|               ...props,
|               tableMaxWidth: this.tableMaxWidth
|             }
 @ ./node_modules/vue-pivottable/src/index.js 2:0-44
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8081 webpack/hot/dev-server ./src/main.ts
```

this is my loader?
```
{
        test: /\.js$/,
        use: utils.scriptLoaders(scriptLoadersOptions).js,
        include: [resolve('src'), resolve('test')]
},
```

**Comment by leonardlin** [comment]
I'm not an export with modules and webpack etc.

but from what I read a module should include a transpiled version.

It seems that this module (downloaded via npm) still needs to be transpiled.

I did this to my loader
```
      {
        test: /\.js$/,
        use: utils.scriptLoaders(scriptLoadersOptions).js,
        include: [resolve('src'), resolve('test'), resolve('node_modules/vue-pivottable')]
      },
```

it compiles and loads now

**Comment by siscovisac** [comment]
I have the same problem as you. In which part of your component do you add the code you mention. I've been looking for a solution for weeks, I appreciate your answer.

 {
        test: /\.js$/,
        use: utils.scriptLoaders(scriptLoadersOptions).js,
        include: [resolve('src'), resolve('test'), resolve('node_modules/vue-pivottable')]
},
?
