### ISSUE TITLE
Example of derivedAttributes please

### ISSUE THREAD

**Issue by adroit91** [Seungwoo321/vue-pivottable#32]
Hi,

I have found it very difficult to use the internal utilities of pivottablejs as derivedAttributes. I have used it as a fixed function that doesn't accept any arguments (and hence, does a fixed transform on every record). It would be great if there were a working example for something like "bin" which is inside your "dist/<>.js" file.

Thanks for the great work.

**Comment by Seungwoo321** [comment]
Please check updated demo example code. [link](https://github.com/Seungwoo321/vue-pivottable/blob/master/demo/example-vue-cli3/src/App.vue)
