### ISSUE TITLE
provide support for custom aggregators

### ISSUE THREAD

**Issue by jbrathwa** [Seungwoo321/vue-pivottable#39]
Currently, both `vue-pivottable` and `vue-pivottable-ui` components use built-in aggregators with only `aggregatorName` as an option. There is no option to add custom aggregators as in the [pivottable.js](https://github.com/nicolaskruchten/pivottable/wiki/Aggregators).  Some option is required to add your own aggregator in the given format.

Also, Thank you for providing this amazing vue port. If you want, I can work on this and add PR.

Thanks

**Comment by Mihailoff** [comment]
This would be helpful, we have an issue with rounding and I believe a custom aggregator could solve this.
