### ISSUE TITLE
Filer out "null" values

### ISSUE THREAD

**Issue by glumb** [Seungwoo321/vue-pivottable#42]
My data is structured like that 

```
[
{form1:question1 (question1): "1"},
{form1:question1 (question1): "6"},
{form1:question2 (question2): "B"},
{form1:question2 (question2): "A"},
]
```

This results in `null` values. How to filter them out?
Deselecting `null` from the filter does not work unfortunately.
![image](https://user-images.githubusercontent.com/3062564/105578002-7cbd2d80-5d7d-11eb-889b-d434f8a5b60d.png)

Also is this possible programmatically?
I tried this, but it did not work:
```js
  'form1:question1 (question1)': {
          'null': true // false
   }
```

**Comment by glumb** [comment]
I have just noticed that the version on NPM may not include your recent fix to that issue. Would you mind updating the NPM package as well? 😃

**Comment by Seungwoo321** [comment]
Sorry, recently fixed issue has not been completed yet.
I will update the NPM package as soon as possible.
