### ISSUE TITLE
Filter "too many to list" -> provide search field?

### ISSUE THREAD

**Issue by khmmrl** [Seungwoo321/vue-pivottable#57]
When trying to filter on columns with many values, "too many to list" is shown and filtering is not possible. 

What is "too many" and would it be a possibility to include a search field to reduce the list size and allow filtering if you know the concrete value?

**Comment by Seungwoo321** [comment]
"Too many" defaults to 500. I think the following link will be helpful to you.

https://seungwoo321.github.io/vue-pivottable/props/#menulimit
