### ISSUE TITLE
what should i add an appropriate loader to handle this when use webpack

### ISSUE THREAD

**Issue by WEIR-ZHONG** [Seungwoo321/vue-pivottable#6]

**Comment by WEIR-ZHONG** [comment]
Module parse failed: Unexpected token (146:8)
You may need an appropriate loader to handle this file type.
|     assignValue (field) {
|       this.propsData.valueFilter = {
|         ...this.propsData.valueFilter,
|         [field]: {}
|       }

**Comment by WEIR-ZHONG** [comment]
after i use webpack label to resolve the ES6 grammer in the vue-pivottable

**Comment by WEIR-ZHONG** [comment]
but seems something wrong after wepback package it

**Comment by scottjo** [comment]
Hi. I am having the same issue. I have defined ES2016 present in my babelrc file yet it is still complaining. Can you please let us know what webpack settings / requirements are. Thanks

**Comment by Seungwoo321** [comment]
Fix #6 61d3470d808061233ae25c7133c98a96074fc2a7
