### ISSUE TITLE
server side data?

### ISSUE THREAD

**Issue by swuecho** [Seungwoo321/vue-pivottable#9]
because all the data is in mem, there is a hard limit on the size of data. 

I am thinking if it is possible to suport fetch data from the backend on the fly. i.e the pivotData source is some table in DB and all the operation on the frontend is translated to the sql query.

**Comment by jupe** [comment]
I think this should be addressed to pivottable -library instead. Doubt that library refactoring to support backend filtering/data is hard, otherwise it would be implemented already I guess..

**Comment by swuecho** [comment]
You are right and there is a issue in the main pivottable lib and the author think it is out of scope or something.
